smu_site/apps/SHC/urls.py
from django.urls import path
from . import views


app_name = "SHC"

urlpatterns = [
    path('', views.index, name='index'),
]

smu_site/apps/info/urls.py
from django.urls import path
from . import views


app_name = 'info'

urlpatterns = [
    path('organization/', views.organization, name='organization'),
    path('institutes/', views.institutes, name='institutes'),
    path('grant/', views.grant, name='grant'),
    path('gzs/', views.gzs, name='gzs'),
    # path('newspage/', views.newspage, name='newspage'),
    path('institutes/<int:inst_id>/', views.institute_info,
         name='institute_info')
]

smu_site/apps/news/urls.py
from django.urls import path
from . import views


app_name = 'news'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:news_id>/', views.newspage, name='newspage'),
    path('events/<int:event_id>/', views.eventpage, name='eventpage'),
]

smu_site/apps/representatives/urls.py
from django.urls import path
from . import views


app_name = 'representatives'

urlpatterns = [
    path('account', views.create_news, name='news'),
    path('account/save_news', views.save_news, name='save_news'),
    path('account/create_scientist', views.create_scientist, name='create_scientist'),
    # path('account/create_new_institute', views.create_new_institute, name='create_institute'),
    # path('account/create_new_grant', views.create_new_grant, name='create_new_grant'),
    path('account/upload_doc', views.upload_doc, name='upload_doc'),
    # path('<int:institute_id>/', views.create_scientist, name='index'),
]

smu_site/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views, settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='main'),
    path('news/', include('news.urls'), name='news'),
    path('documents/', include('documents.urls')),
    path('info/', include('info.urls')),
    path('moderators/', include('moderators.urls')),
    path('accounts/login', include('django.contrib.auth.urls')),
    path('accounts/login', views.user_login, name='user_login'),
    # path('representatives/', include(
    #      ('representatives.urls', 'representatives'),
    #      namespace='representatives')),
    path('representatives/', include('representatives.urls')),
    path('SHC/', include('SHC.urls')),
    path('delete/<str:obj_type>/<int:id>', views.readelete, name='delete_news'),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

smu_site/apps/SHC/models.py
from django.db import models


class Doc(models.Model):
    doc = models.OneToOneField('documents.Doc',
                               on_delete=models.CASCADE,
                               verbose_name='id документа',
                               primary_key=True)
    description = models.TextField('Описание документа')
    on_changed = models.BigIntegerField('ID заменяемой записи',
                                        null=True)

smu_site/apps/documents/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField("Название категории", max_length=300)


class Doc(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    queue = models.OneToOneField("moderators.Queue",
                                 on_delete=models.SET_NULL, null=True)
    name = models.CharField("Название документа", max_length=100)

    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 null=True)
    
    def _img_dir_path(self, filename):
        return (f'documents/'
                f'{self.category.name}'
                f'/{filename}')
    
    path = models.FileField("Путь до документа",
                            upload_to=_img_dir_path)
    

smu_site/apps/moderators/models.py
from django.db import models


class Queue(models.Model):
    CHOICES = (
        ('doc', 'Документ'),
        ('news', 'Новость'),
        ('event', 'Мероприятие/событие'),
        ('scientist', 'Учёный')
    )
    obj_type = models.CharField("Тип объекта",
                                max_length=10, choices=CHOICES)
    
    SCHOICES = (
        ('pub', 'Публикация'),
        ('chg', 'Изменение'),
        ('del', 'Удаление')
    )
    status = models.CharField("Статус запрашиваемого объекта",
                              max_length=10, choices=SCHOICES,
                              default='Публикация')
    
    class Meta:
        verbose_name = 'Очередь'
        verbose_name_plural = 'Очереди'

smu_site/apps/representatives/models.py
from django.contrib.auth.models import User
from django.db import models


class ReprInst(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             verbose_name="Представитель")
    institute = models.ForeignKey("info.Institute",
                                  on_delete=models.DO_NOTHING,
                                  verbose_name="Представитель")

smu_site/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth import authenticate


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Имя пользователя",
        'required': "",
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'id': "myInput",
        'placeholder': "пароль",
        'required': "",
    }))

    def clean_password(self):
        cd = self.cleaned_data
        user = authenticate(username=cd['username'], password=cd['password'])
        if user is None:
            raise ValidationError('')
        return cd['password']

    def clean_username(self):
        cd = self.cleaned_data
        return cd['username']

smu_site/apps/SHC/views.py
from django.conf import settings
from django.shortcuts import render
# from documents.models import Doc
from .models import Doc as SHCDoc


def index(request):
    documents = (SHCDoc.objects.select_related('documents.doc')
                 .filter(doc__queue_id__isnull=True)
                 .order_by('documents.doc__id'))
    # print(documents)
    return render(request, 'SHC/index.html',
                  {'docs': documents, 'media': settings.MEDIA_URL})

smu_site/apps/documents/views.py
from django.shortcuts import render
from django.conf import settings
from .models import Category, Doc


def index(request):
    docs = (Doc.objects.select_related('category')
            .filter(queue_id__isnull=True,
                    category__isnull=False).order_by('category__name',
                                                     'name'))
    docs_content = {}
    for d in docs:
        if not docs_content.get(d.category.name):
            docs_content[d.category.name] = ["", 0]

        docs_content[d.category.name][0] += (
            "<div class='doc_content_stuff'>"
            f"<a href='{settings.MEDIA_URL}"
            f"{d.path}'>{d.name}</a></div>\n")
        docs_content[d.category.name][1] = d.id

    return render(request, 'info/documents.html',
                  {'title': "Документы",
                   'categories': [(c, *docs_content[c]) for c in docs_content],
                   "is_moder": request.user.groups.filter(name='moderator').exists(),
                   "is_repr": request.user.groups.filter(name='representative').exists()
                   })

smu_site/apps/info/views.py
import configparser

from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, Http404

from info.models import Institute, Scientist, Grant
from news.models import Image
from SHC.models import Doc as SHCDoc


config = configparser.ConfigParser()
config.read('config.ini')


# def newspage(request):
#     return render(request, 'info/newspage.html')

def institutes(request):
    inst = Institute.objects.all().order_by('name')
    inst = [(i, Image.objects.filter(institute_id=i.id)
             .order_by('id').first())
            for i in inst]
    return render(request, 'info/institutes.html',
                  {'institutes': inst,
                   "is_moder": request.user.groups.filter(
                       name='moderator').exists(),
                   "is_repr": request.user.groups.filter(
                       name='representative').exists()
                   })


def grant(request):
    grants = (Grant.objects.filter(queue_id__isnull=True)
              .order_by('end_doc_date'))
    grants = [(g, Image.objects.filter(grant_id=g.id)
               .order_by('id').first())
              for g in grants]
    
    p = Paginator(grants, int(config["news"]["grants_per_page"]))
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        # Если page_number не является целым числом, то присваивается 1
        page_obj = p.page(1)
    except EmptyPage:
        # Если страница пустая, возвращает последнюю страницу
        page_obj = p.page(p.num_pages)
        
    return render(request, 'info/grant.html',
                  {'grants': page_obj,
                   "is_moder": request.user.groups
                   .filter(name='moderator').exists(),
                   "is_repr": request.user.groups
                   .filter(name='representative').exists()
                   })


def organization(request):
    return render(request, 'info/organization.html',
                  {
                      "is_moder": request.user.groups
                      .filter(name='moderator').exists(),
                      "is_repr": request.user.groups
                      .filter(name='representative').exists()})


def gzs(request):
    documents = (SHCDoc.objects.select_related('doc')
                 .filter(doc__queue_id__isnull=True)
                 .order_by('doc__id'))
    return render(request, 'info/gzs.html',
                  {
                      'docs': documents,
                      'media': settings.MEDIA_URL,
                      "is_moder": request.user.groups
                      .filter(name='moderator').exists(),
                      "is_repr": request.user.groups
                      .filter(name='representative').exists()})


def institute_info(request, inst_id):
    try:
        inst = Institute.objects.get(id=inst_id)
    except:
        return Http404('Институт не найден')
    
    inst_img = Image.objects.filter(institute_id=inst_id).first()
    scientists = (Scientist.objects.filter(institute_id=inst_id,
                                           queue_id__isnull=True)
                  .order_by('name'))
    scientists = [(s, Image.objects.filter(scientist_id=s.id)
                   .order_by('id').first())
                  for s in scientists]
    return render(request, 'info/institute_info.html',
                  {
                      'institute': inst,
                      'inst_img': inst_img,
                      'scientists': scientists,
                      "is_moder": request.user.groups.filter(
                          name='moderator').exists(),
                      "is_repr": request.user.groups.filter(
                          name='representative').exists()
                  })

smu_site/apps/news/views.py
import configparser

from bs4 import BeautifulSoup as BS
from datetime import date, timedelta
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from django.shortcuts import render
from django.utils.timezone import localdate

from .models import News, Event, Image
from info.models import Grant


def newspage(request, news_id):
    try:
        news = News.objects.get(id=news_id)
    except:
        return Http404('Такой новости не существует')
    
    month = ['Янв', 'Февр', 'Март', 'Апр', 'Май', 'Июнь',
             'Июль', 'Авг', 'Сент', 'Окт', 'Нояб', 'Дек']
    m = month[news.pub_date.month - 1]
    
    img = Image.get_related_images(news_id, 'news')
    if img:
        img = img[0]
    
    return render(request, 'news/newspage.html',
                  {'content': news, 'type': 'news',
                   'img': img, 'month': m,
                   "is_moder": request.user.groups
                   .filter(name='moderator').exists(),
                   "is_repr": request.user.groups
                   .filter(name='representative').exists()})


def eventpage(request, event_id):
    try:
        event = Event.objects.get(id=event_id)
    except:
        return Http404('Такой новости не существует')
    
    month = ['Янв', 'Февр', 'Март', 'Апр', 'Май', 'Июнь',
             'Июль', 'Авг', 'Сент', 'Окт', 'Нояб', 'Дек']
    m = month[event.pub_date.month - 1]
    
    img = Image.get_related_images(event_id, 'event')
    if img:
        img = img[0]
        
    return render(request, 'news/newspage.html',
                  {'content': event, 'type': 'event', 'img': img,
                   'month': m,
                   "is_moder": request.user.groups
                   .filter(name='moderator').exists(),
                   "is_repr": request.user.groups
                   .filter(name='representative').exists()})


config = configparser.ConfigParser()  # создаём объекта парсера
config.read("config.ini")


def index(request):
    # Получаем даты для фильтрации списка новостей
    sdate = date.fromisoformat(
        request.POST.get("start-date", "2023-11-28"))
    edate = date.fromisoformat(
        request.POST.get("end-date", localdate().isoformat()))
    edate += timedelta(days=1)
    
    # Выбираем те новости и события, которые не находятся в очереди
    last_news = News.objects.filter(
        pub_date__range=(sdate, edate), queue_id__isnull=True)
    last_news = [(n, Image.objects.filter(news_id=n.id).first())
                 for n in last_news]
    last_events = Event.objects.filter(
        pub_date__range=(sdate, edate), queue_id__isnull=True)
    last_events = [(e, Image.objects.filter(event_id=e.id).first())
                   for e in last_events]
    last_news += last_events
    
    # Сортируем по дате и выбираем первые 5 для первой страницы новостей
    # в будущем нужно реализовать pagination
    last_news = list(sorted(last_news, key=lambda x: x[0].pub_date,
                            reverse=True))
    
    # функция для сокращения текста
    def trim_text(text: str, limit):
        if len(text) < limit:
            return text
        
        si1 = text.find('. ')
        si2 = text.find('! ')
        si3 = text.find('? ')
        if max(si1, si2, si3) != -1:
            si = min(i for i in (si1, si2, si3) if i != -1)
            if si < limit:
                return text[:si + 2] + trim_text(text[si + 2:],
                                                 limit - si - 1)
        
        if ' ' in text:
            t = ''
            for w in text.split(' '):
                if len(t) + len(w) < limit:
                    t += w + ' '
                else:
                    break
            
            return t + ' ...'
        
        return text[:limit - 3] + '...'
    
    # объединяем со списков месяцев и кратким текстом
    month = ['Янв', 'Февр', 'Март', 'Апр', 'Май', 'Июнь',
             'Июль', 'Авг', 'Сент', 'Окт', 'Нояб', 'Дек']
    last_news = [('news' if isinstance(n, News) else 'event',
                  n, month[n.pub_date.month - 1],
                  trim_text(BS(n.text, 'html.parser')
                            .select_one('p').text, 280), img)
                 for n, img in last_news]
    
    p = Paginator(last_news, int(config["news"]["news_per_page"]))
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        # Если page_number не является целым числом, то присваивается 1
        page_obj = p.page(1)
    except EmptyPage:
        # Если страница пустая, возвращает последнюю страницу
        page_obj = p.page(p.num_pages)
    
    # переводим даты в изначальный формат
    sdate = sdate.isoformat()
    edate -= timedelta(days=1)
    edate = edate.isoformat()
    
    # Получаем актуальные события и гранты
    events = (Event.objects.filter(queue_id__isnull=True)
              .order_by('begin_date', '-pub_date'))[
             :int(config["news"]["events_per_page"])]
    events = [(e, trim_text(BS(e.text, 'html.parser')
                            .select_one('p').text, 180))
              for e in events]
    grants = (Grant.objects.filter(queue_id__isnull=True)
              .order_by('end_doc_date'))[:3]
    
    return render(request, 'index.html',
                  {
                      "is_moder": request.user.groups
                  .filter(name='moderator').exists(),
                      "is_repr": request.user.groups
                  .filter(name='representative').exists(),
                      "last_news": page_obj,
                      "sdate": sdate,
                      "edate": edate,
                      "events": events,
                      "grants": grants
                  })

smu_site/templates/representatives/create_scientist.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Responsive Animated Navbar{% endblock %}
{% block meta %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="keywords" content="">
    <meta name="description" content="">
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/fontawesome.min.css" integrity="sha512-siarrzI1u3pCqFG2LEzi87McrBmq6Tp7juVsdmGY1Dr8Saw+ZBAzDzrGwX3vgxX1NkioYNCFOVC0GpDPss10zQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
	<script src="https://cdn.tiny.cloud/1/x9fbifsbf9wgj1k6nbzyfyhabvwcsb9ewleh0lajmfbfnvip/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
{% endblock %}
{% block content %}
	{% include "navbar.html" %}
	{% include "representatives/rep_navbar.html" %}
	<div class="place_form main_plate plates_home container-custom plate-container">
		<div class="decorate_form plates col-lg-12 col-sm-12 col-md-12 col-xs-12">
			<form class="form_all" action="" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="Intoform col-lg-12 col-sm-12 col-md-12 col-xs-12">
					<div class="First plates col-lg-5 col-sm-5 col-md-5 col-xs-5">
						<br>
						<label class="labels_for_form" for="name">Имя учёного:</label>
						{{form.name}}
						<br>
						<label class="labels_for_form" for="position">Должность:</label>
						{{form.position}}
						<br>
						<label class="labels_for_form" for="degree">Учёная степень:</label>
						{{form.degree}}
						<br>
						<label class="labels_for_form" for="lab">Лаборатория:</label>
						{{form.lab}}
						<br>
						<label class="labels_for_form" for="imageInput">Фотография учёного:</label>
						{{form.url_path}}
					</div>
					<div class="First plates col-lg-6 col-sm-6 col-md-6 col-xs-6">
						<br>
						<label class="labels_for_form" for="service_name">Ссылки на профили:</label>
						{{form.service_name}}
						<br>
						<label class="labels_for_form" for="scientific_interests">Научные интересы:</label>
						{{form.scientific_interests}}
						<br>
					</div>
				</div>
				<input class="submit_all labels_for_form plates col-lg-2 col-sm-2 col-md-2 col-xs-2" type="submit" value="Опубликовать">
			</form>
		</div>
	</div>
	{% include "footer.html" %}

{% endblock %}

smu_site/templates/representatives/news.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Добавление новостей и мероприятий{% endblock %}
{% block meta %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="keywords" content="">
    <meta name="description" content="">
{% endblock %}
<!-- IconFont and Stylesheet -->
{% block link %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/fontawesome.min.css" integrity="sha512-siarrzI1u3pCqFG2LEzi87McrBmq6Tp7juVsdmGY1Dr8Saw+ZBAzDzrGwX3vgxX1NkioYNCFOVC0GpDPss10zQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
	<script src="https://cdn.tiny.cloud/1/x9fbifsbf9wgj1k6nbzyfyhabvwcsb9ewleh0lajmfbfnvip/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
	<style>
		.tox-collection__item-icon  svg {
			color:black !important;
		}
		.tox-icon svg {
			color:black !important;
		}
	</style>
	<script type="text/javascript">
		tinymce.init({
			selector: '#myTextarea',

			plugins: [
			'advlist', 'autolink', 'link', 'image', 'lists', 'charmap', 'preview', 'anchor', 'pagebreak',
			'searchreplace', 'wordcount', 'visualblocks', 'visualchars', 'code', 'fullscreen', 'insertdatetime',
			'media', 'table', 'emoticons', 'template'
			],
			toolbar: 'undo redo | styles | bold italic | alignleft aligncenter alignright alignjustify | ' +
			'bullist numlist outdent indent | link image | print preview media fullscreen | ' +
			'forecolor backcolor emoticons | help | googlemap',

			setup: function (editor) {
			  editor.ui.registry.addButton('googlemap', {
				text: 'Insert Map',
				onAction: function () {
				  let link = prompt("Enter the link here.");

				  if(link != ""){
					const mapCode = '<iframe src="' + link + '" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>';
					editor.insertContent(mapCode);
				  }
				},
			  });
			},
            /* Block popup (DO NOT REMOVE COMMENTS)
			init_instance_callback : function(editor) {
				var freeTiny = document.querySelector('.tox .tox-notification--in');
			   freeTiny.style.display = 'none';
			  },*/
			menu: {
			favs: { title: 'My Favorites', items: 'code visualaid | searchreplace | emoticons' }
			},
			menubar: 'favs file edit view insert format tools table help',


            image_title: true,
            // enable automatic uploads of images represented by blob or data URIs
            automatic_uploads: true,
            // add custom filepicker only to Image dialog
            file_picker_types: 'image',
            file_picker_callback: function(cb, value, meta) {
                var input = document.createElement('input');
                input.setAttribute('type', 'file');
                input.setAttribute('accept', 'image/*');

                input.onchange = function() {
                    var file = this.files[0];
                    var reader = new FileReader();

                    reader.onload = function () {
                        var id = 'blobid' + (new Date()).getTime();
                        var blobCache =  tinymce.activeEditor.editorUpload.blobCache;
                        var base64 = reader.result.split(',')[1];
                        var blobInfo = blobCache.create(id, file, base64);
                        blobCache.add(blobInfo);

                        // call the callback and populate the Title field with the file name
                        cb(blobInfo.blobUri(), { title: file.name });
                    };
                    reader.readAsDataURL(file);
                };

                input.click();
            }
        });
		</script>

		<script>
			function call() {
			  var content =tinymce.get("myTextarea").getContent();
			  var blob = new Blob([content], { type: "text/plain" });

			  var a = document.createElement("a");
			  a.href = URL.createObjectURL(blob);
			  a.download = "output.txt";
			  document.body.appendChild(a);
			  a.click();
			  document.body.removeChild(a);
			}
		  </script>

		<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
		<script>
		$(document).ready(function() {
			$('.for_event').hide();
				// Show/hide institute-related elements based on user group selection
				$('#NewEvents').change(function() {
					  if ($(this).val() === 'News') {
						$('.for_event').hide();
					  } else {
						$('.for_event').show();
					  }
				});
			});
		</script>
{% endblock %}
<!--//-->



{% block content %}
	<div class="z-index:3">
        {% include "navbar.html" %}
	    {% include "representatives/rep_navbar.html" %}
    </div>

    <script>
          function save() {
            var content = tinymce.get('myTextarea').getContent();
            var titleElement = document.getElementById('myTitle');
            var imageInput = document.getElementById('imageInput');
            var categoryInput = document.getElementById('NewEvents');
            var startInput = document.getElementById('startDate');
            var endInput = document.getElementById('endDate');
            var data = new FormData();
              data.append('text', content);
              data.append('title', titleElement.value);
              data.append('image', imageInput.files[0]);
              data.append('category', categoryInput.value);
              data.append('start', startInput.value);
              data.append('end', endInput.value);

            fetch('{% url 'representatives:save_news' %}', {
                method: 'POST',
                body: data  // Теперь мы отправляем объект FormData, а не JSON
                // Заголовок 'Content-Type' не указываем, т.к. браузер автоматически определит правильный тип контента для FormData
              })
              .then(response => response.json())
              .then(data => {
                console.log('Успешно:', data);
              })
              .catch((error) => {
                console.error('Ошибка:', error);
              });
          }
    </script>


	<div class="place_form main_plate plates_home container-custom plate-container">
        <form class="form_all" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="decorate_form plates col-lg-12 col-sm-12 col-md-12 col-xs-12" >
                <div style="position:relative; z-index:1" class="labels_for_form container-custom">
                    <div class="pt-4 col-lg-12 col-md-12 col-sm-12">
                        <textarea id="myTextarea" style="width:100%"></textarea>
                    </div>

                </div>

                <div class="container-custom">
                        <input type="text" id="myTitle" class="form-control mt-2 labels_for_form platesx" style="height:4em; margin-bottom:1em" placeholder="Название новости" required/>
                        <label class="labels_for_form" for="imageInput"> Прикрепление основного изображения: </label>
                        <input class="input_for_form_img" type="file" id="imageInput" name="image" accept=".jpg, .jpeg, .png">
                        <input class="labels_for_form mt-1 mb-1 plates col-lg-5 col-sm-5 col-md-5 col-xs-5 btn" type="button" onclick="call()" value="Показать сгенерированный HRML-код">
                        <label  class="mt-2 labels_for_form inst" for="NewEvents">Категория публикации</label>
                        <select class="form-control input_for_form text-dark" id="NewEvents" name="NewEvents">
                            <option value="News">Новость</option>
                            <option value="Events">Мероприятие</option>
                        </select>
                        <div class="for_event">
                            <label class="labels_for_form" for="startDate">Дата начала мероприятия:</label>
                            <input class="input_for_form" type="datetime-local" id="startDate" name="startDate">
                            <label class="labels_for_form" for="endDate">Дата окончания мероприятия:</label>
                            <input class="input_for_form" type="datetime-local" id="endDate" name="endDate">
                        </div>
                        <input class="submit_all labels_for_form plates mt-3 mb-3  col-lg-2 col-sm-2 col-md-2 col-xs-2" type="submit" onclick="save()" value="Опубликовать">
                </div>
            </div>
        </form>
	</div>

    {% include "footer.html" %}
 
{% endblock %}

smu_site/templates/representatives/rep_navbar.html
	<div class="plates_home container-custom plate-container">
		<div class="Navbar_Moder plates col-lg-12 col-sm-12 col-md-12 col-xs-12 p-5">
			<div class="links mr-2 mt-2 mb-2 col-lg-2 col-sm-2 col-md-2 col-xs-2">
				<a class="stretched-link" href="{% url 'representatives:news' %}">Новости</a>
			</div>
			<div class="links m-2 col-lg-2 col-sm-2 col-md-2 col-xs-2">
				<a class="stretched-link" href="{% url 'representatives:create_scientist' %}">Учёные</a>
			</div>
<!--            <div class="links ml-2 mt-2 mb-2 col-lg-2 col-sm-2 col-md-2 col-xs-2">-->
<!--				<a class="stretched-link" href="{# url 'representatives:create_institute' #}">Институты</a>-->
<!--			</div>-->
<!--			<div class="links m-2 col-lg-2 col-sm-2 col-md-2 col-xs-2">-->
<!--				<a class="stretched-link" href="{# url 'representatives:create_new_grant' #}">Гранты</a>-->
<!--			</div>-->
			<div class="links ml-2 mt-2 mb-2 col-lg-2 col-sm-2 col-md-2 col-xs-2">
				<a class="stretched-link" href="{% url 'representatives:upload_doc' %}">Документы</a>
			</div>
		</div>
	</div>