smu_site/apps/SHC/urls.py
from django.urls import path
from . import views


app_name = "SHC"

urlpatterns = [
    path('', views.index, name='index'),
]

smu_site/apps/info/urls.py
from django.urls import path
from . import views


app_name = 'info'

urlpatterns = [
    path('organization/', views.organization, name='organization'),
    path('institutes/', views.institutes, name='institutes'),
    path('grant/', views.grant, name='grant'),
    path('gzs/', views.gzs, name='gzs'),
    # path('newspage/', views.newspage, name='newspage'),
    path('institutes/<int:inst_id>/', views.institute_info,
         name='institute_info')
]

smu_site/apps/news/urls.py
from django.urls import path
from . import views


app_name = 'news'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:news_id>/', views.newspage, name='newspage'),
    path('events/<int:event_id>/', views.eventpage, name='eventpage'),
]

smu_site/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views, settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='main'),
    path('news/', include('news.urls'), name='news'),
    path('documents/', include('documents.urls')),
    path('info/', include('info.urls')),
    path('moderators/', include('moderators.urls')),
    path('accounts/login', include('django.contrib.auth.urls')),
    path('accounts/login', views.user_login, name='user_login'),
    # path('representatives/', include(
    #      ('representatives.urls', 'representatives'),
    #      namespace='representatives')),
    path('representatives/', include('representatives.urls')),
    path('SHC/', include('SHC.urls')),
    path('delete/<str:obj_type>/<int:id>', views.readelete, name='delete_news'),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

smu_site/apps/SHC/views.py
from django.conf import settings
from django.shortcuts import render
# from documents.models import Doc
from .models import Doc as SHCDoc


def index(request):
    documents = (SHCDoc.objects.select_related('documents.doc')
                 .filter(doc__queue_id__isnull=True)
                 .order_by('documents.doc__id'))
    # print(documents)
    return render(request, 'SHC/index.html',
                  {'docs': documents, 'media': settings.MEDIA_URL})

smu_site/apps/documents/views.py
from django.shortcuts import render
from django.conf import settings
from .models import Category, Doc


def index(request):
    docs = (Doc.objects.select_related('category')
            .filter(queue_id__isnull=True,
                    category__isnull=False).order_by('category__name',
                                                     'name'))
    docs_content = {}
    for d in docs:
        if not docs_content.get(d.category.name):
            docs_content[d.category.name] = ["", 0]

        docs_content[d.category.name][0] += (
            "<div class='doc_content_stuff'>"
            f"<a href='{settings.MEDIA_URL}"
            f"{d.path}'>{d.name}</a></div>\n")
        docs_content[d.category.name][1] = d.id

    return render(request, 'info/documents.html',
                  {'title': "Документы",
                   'categories': [(c, *docs_content[c]) for c in docs_content],
                   "is_moder": request.user.groups.filter(name='moderator').exists(),
                   "is_repr": request.user.groups.filter(name='representative').exists()
                   })

smu_site/apps/info/views.py
import configparser

from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, Http404

from info.models import Institute, Scientist, Grant
from news.models import Image
from SHC.models import Doc as SHCDoc


config = configparser.ConfigParser()
config.read('config.ini')


# def newspage(request):
#     return render(request, 'info/newspage.html')

def institutes(request):
    inst = Institute.objects.all().order_by('name')
    inst = [(i, Image.objects.filter(institute_id=i.id)
             .order_by('id').first())
            for i in inst]
    return render(request, 'info/institutes.html',
                  {'institutes': inst,
                   "is_moder": request.user.groups.filter(
                       name='moderator').exists(),
                   "is_repr": request.user.groups.filter(
                       name='representative').exists()
                   })


def grant(request):
    grants = (Grant.objects.filter(queue_id__isnull=True)
              .order_by('end_doc_date'))
    grants = [(g, Image.objects.filter(grant_id=g.id)
               .order_by('id').first())
              for g in grants]
    
    p = Paginator(grants, int(config["news"]["grants_per_page"]))
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        # Если page_number не является целым числом, то присваивается 1
        page_obj = p.page(1)
    except EmptyPage:
        # Если страница пустая, возвращает последнюю страницу
        page_obj = p.page(p.num_pages)
        
    return render(request, 'info/grant.html',
                  {'grants': page_obj,
                   "is_moder": request.user.groups
                   .filter(name='moderator').exists(),
                   "is_repr": request.user.groups
                   .filter(name='representative').exists()
                   })


def organization(request):
    return render(request, 'info/organization.html',
                  {
                      "is_moder": request.user.groups
                      .filter(name='moderator').exists(),
                      "is_repr": request.user.groups
                      .filter(name='representative').exists()})


def gzs(request):
    documents = (SHCDoc.objects.select_related('doc')
                 .filter(doc__queue_id__isnull=True)
                 .order_by('doc__id'))
    return render(request, 'info/gzs.html',
                  {
                      'docs': documents,
                      'media': settings.MEDIA_URL,
                      "is_moder": request.user.groups
                      .filter(name='moderator').exists(),
                      "is_repr": request.user.groups
                      .filter(name='representative').exists()})


def institute_info(request, inst_id):
    try:
        inst = Institute.objects.get(id=inst_id)
    except:
        return Http404('Институт не найден')
    
    inst_img = Image.objects.filter(institute_id=inst_id).first()
    scientists = (Scientist.objects.filter(institute_id=inst_id,
                                           queue_id__isnull=True)
                  .order_by('name'))
    scientists = [(s, Image.objects.filter(scientist_id=s.id)
                   .order_by('id').first())
                  for s in scientists]
    return render(request, 'info/institute_info.html',
                  {
                      'institute': inst,
                      'inst_img': inst_img,
                      'scientists': scientists,
                      "is_moder": request.user.groups.filter(
                          name='moderator').exists(),
                      "is_repr": request.user.groups.filter(
                          name='representative').exists()
                  })

smu_site/apps/moderators/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group
from django.db import transaction
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render
from .forms import (CreateUserForm, CreateGrantForm, CreateInstituteForm, UploadSHCDocForm,
                    CreateScientistForm, UploadDocForm)
from .models import Queue
from documents.models import Doc, Category
from info.models import Grant, Institute, Scientist, ScientistLink
from news.models import News, Event, Image
from representatives.models import ReprInst
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
# import json
# from django.views import View
# from django.core.files.base import ContentFile
# import base64
# from django.core.files.storage import default_storage


@transaction.atomic
@login_required
@permission_required('auth.moderator', raise_exception=True)
def add_new_documents(request):
    if request.method == "POST":
        form = UploadDocForm(request.POST, request.FILES)
        if form.is_valid():
            if form.cleaned_data['Choose_Category'] == 'True':
                cat = Category(name=form.cleaned_data['New_category'])
                cat.save()
                doc = Doc(path=request.FILES["path"],
                          name=form.cleaned_data['name'],
                          category_id=cat.id, user_id=request.user.id)
                doc.save()
            else:
                doc = Doc(path=request.FILES["path"],
                          name=form.cleaned_data['name'],
                          category_id=form.cleaned_data['Category'],
                          user_id=request.user.id)
                doc.save()
                
            return HttpResponseRedirect('/moderators/account')
    else:
        form = UploadDocForm()
        
    return render(request, "moderators/add_new_documents.html", {
        "form": form,
        "is_moder": request.user.groups.filter(name='moderator').exists(),
        "is_repr": request.user.groups.filter(name='representative').exists()
    })


@transaction.atomic
@login_required
@permission_required('auth.moderator', raise_exception=True)
def moder_guests(request):
    moder_queue = []
    obtp = {'doc': ('Документ', Doc),
            'news': ('Новость', News),
            'event': ('Мероприятие', Event),
            'scientist': ('Учёный', Scientist)}
    for q in Queue.objects.all():
        try:
            moder_queue.append((obtp[q.obj_type][0],
                                obtp[q.obj_type][1]
                                .objects.get(queue_id=q.id)))
        except:
            q.delete()

    return render(request, 'moderators/moder_guests.html', {
        'queue': moder_queue, 'range': range(20),
        "is_moder": request.user.groups.filter(name='moderator').exists(),
        "is_repr": request.user.groups.filter(name='representative').exists()
    })


@transaction.atomic
@login_required
@permission_required('auth.moderator', raise_exception=True)
def gzs(request):
    if request.method == 'POST':
        form = UploadSHCDocForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/moderators/account')
    else:
        form = UploadSHCDocForm()

    return render(request, 'moderators/gzs.html', {
        'form': form,
        "is_moder": request.user.groups.filter(name='moderator').exists(),
        "is_repr": request.user.groups.filter(name='representative').exists()
    })


@transaction.atomic
@login_required
@permission_required('auth.moderator', raise_exception=True)
def add_new_guests(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(username=form.cleaned_data['user_name'],
                                            email=form.cleaned_data['email'],
                                            password=form.cleaned_data['password'])
            user_group = Group.objects.get(name=form.cleaned_data['user_group'])
            user.groups.add(user_group)
            rep_inst = ReprInst(
                user_id=user.id,
                institute_id=form.cleaned_data['user_institute'])
            rep_inst.save()
    else:
        form = CreateUserForm()

    return render(request, 'moderators/add_new_guests.html', {
        'form': form,
        "is_moder": request.user.groups.filter(name='moderator').exists(),
        "is_repr": request.user.groups.filter(name='representative').exists()
    })


@transaction.atomic
@login_required
@permission_required('auth.moderator', raise_exception=True)
def create_new_grant(request):
    if request.method == 'POST':

        form = CreateGrantForm(request.POST, request.FILES)

        if form.is_valid():
            grant = Grant(name=form.cleaned_data['name'],
                          criteria=form.cleaned_data['criteria'],
                          description=form.cleaned_data['description'],
                          end_doc_date=form.cleaned_data['end_doc_date'],
                          end_result_date=form.cleaned_data['end_result_date'],
                          link=form.cleaned_data['link'])
            grant.save()
            img = Image(grant_id=grant.id,
                        url_path=request.FILES['url_path'])
            img.save()

            return HttpResponseRedirect('/moderators/account')  # редирект
    else:
        form = CreateGrantForm()

    return render(request, 'moderators/create_new_grant.html', {
        'form': form,
        "is_moder": request.user.groups.filter(name='moderator').exists(),
        "is_repr": request.user.groups.filter(name='representative').exists()
    })


@transaction.atomic
@login_required
@permission_required('auth.moderator', raise_exception=True)
def create_new_institute(request):
    if request.method == 'POST':
        form = CreateInstituteForm(request.POST, request.FILES)
        if form.is_valid():
            # institute = Institute(name=form.cleaned_data['name'],
            #                       description=form.cleaned_data['description'],
            #                       emplotees_count=form.cleaned_data['employees_count'],
            #                       scientist_count=form.cleaned_data['scientist_count'],
            #                       chairman=form.cleaned_data['chairman'],
            #                       link=form.cleaned_data['link'],
            #                       smu_link=form.cleaned_data['smu_link'])
            # institute.save()
            form.save()

            return HttpResponseRedirect('/moderators/account')

    else:
        form = CreateInstituteForm()

    return render(request, 'moderators/create_new_institute.html', {
        'form': form,
        "is_moder": request.user.groups.filter(name='moderator').exists(),
        "is_repr": request.user.groups.filter(name='representative').exists()
    })


@transaction.atomic
@login_required
@permission_required('auth.moderator', raise_exception=True)
def create_scientist(request):
    if request.method == 'POST':

        form = CreateScientistForm(request.POST, request.FILES)

        if form.is_valid():
            print(repr(form.cleaned_data['institute']))
            scientist = Scientist(institute_id=form.cleaned_data['institute'],
                                  name=form.cleaned_data['name'],
                                  lab=form.cleaned_data['lab'],
                                  position=form.cleaned_data['position'],
                                  degree=form.cleaned_data['degree'],
                                  scientific_interests=form.cleaned_data['scientific_interests'],
                                  user_id=request.user.id)
            scientist.save()
            
            links = form.cleaned_data['link'].split('\n')
            for link in links:
                desc, link = link.rsplit(' ', 1)
                lnk = ScientistLink(scientist_id=scientist.id,
                                    link=link, service_name=desc)
                lnk.save()
                
            img = Image(scientist_id=scientist.id,
                        url_path=request.FILES['url_path'],
                        alt=form.cleaned_data['name'])
            img.save()
        # else:
        #     res = 'o_o\n'
        #     for e in form.errors:
        #         res += str(e)
        #     return HttpResponse(res)

    else:
        form = CreateScientistForm()

    return render(request, 'moderators/create_scientist.html', {
            'form': form,
            "is_moder": request.user.groups.filter(name='moderator').exists(),
            "is_repr": request.user.groups.filter(name='representative').exists()
        })


@transaction.atomic
@login_required
@permission_required('auth.moderator', raise_exception=True)
def create_news(request):
    return render(request, "moderators/news.html",
                  {
                      "is_moder": request.user.groups.filter(name='moderator').exists(),
                      "is_repr": request.user.groups.filter(name='representative').exists()
                  })


@csrf_exempt
@transaction.atomic
@require_POST
def save_news(request):
    try:
        # Получение содержимого из запроса
        title = request.POST.get('title')
        text = request.POST.get('text')
        image = request.FILES.get('image')
        category = request.POST.get('category')
        if category == 'Events':
            start = request.POST.get('start')
            end = request.POST.get('end')
            obj = Event(title=title, text=text,
                        user_id=request.user.id,
                        begin_date=start,
                        end_date=end)
            obj.save()
            img = Image(url_path=image, event_id=obj.id)

smu_site/templates/info/gzs.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Государственный жилищный сертификат{% endblock %}
{% block meta %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="keywords" content="">
    <meta name="description" content="">
{% endblock %}
<!-- IconFont and Stylesheet -->
{% block link %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/fontawesome.min.css" integrity="sha512-siarrzI1u3pCqFG2LEzi87McrBmq6Tp7juVsdmGY1Dr8Saw+ZBAzDzrGwX3vgxX1NkioYNCFOVC0GpDPss10zQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js'></script>
{% endblock %}
<!--//-->

{% block content %}
    
    {% include "navbar.html" %}


    <div class="plates_home main_plate container-custom plate-container">
		<h4 class="mb-4 mt-5 " style="font-size:23px; color:var(--nav-bg)">ЛЕНТА ГЖС</h4>
		{% for doc in docs %}
		<hr style="color:var(--nav-btn-bg)">
		<div class="plates col-lg-12 col-sm-12 col-md-12 col-xs-12 d-flex flex-row ">
			<div class="d-flex flex-column col-lg-8 col-sm-8 col-md-8 col-xs-8 NameAndDesc">
				<div class="Names m-2">
					<div style="color:grey; font-size:18px" class="mt-2 col-lg-4 col-sm-4 col-md-4 col-xs-4">
						Название документа
					</div>	
					<hr style="color:silver">
					<div class="p-1 m-2 col-lg-8 col-sm-8 col-md-8 col-xs-8 text-dark">
						{{doc.doc.name}}
					</div>
				</div>
				<div class="description m-2">
					<div style="color:grey; font-size:18px" class="col-lg-4 col-sm-4 col-md-4 col-xs-4">
						Описание документа
					</div>
					<hr style="color:silver">					
					<div class="p-1 m-2 col-lg-8 col-sm-8 col-md-8 col-xs-8 text-dark">
						{{doc.description}}
					</div>
				</div>
			</div>
			<div class="LinkTOGzs col-lg-4 col-sm-4 col-md-4 col-xs-4 d-flex justify-content-center flex-column align-items-center p-3">
				<div class="plates mt-2 GZS col-lg-12 col-sm-12 col-md-12 col-xs-12 d-flex justify-content-center align-items-center p-5 mb-3">
                    <a href="{{media}}{{doc.doc.path}}" class="text-white stretched-link linkGzs m-0 p-0 text-center">**ССылка на документ**</a>
                </div>
				    {% if user.is_authenticated %}
                      {% if is_moder or user.is_superuser %}
                          <a href="/delete/gzs/{{ doc.doc.id }}" class="btn-del">удалить</a>
                      {% endif %}
                    {% endif %}
			</div>
		</div>
		{% endfor %}
	</div>


    {% include "footer.html" %}


{% endblock %}

smu_site/templates/info/institutes.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Институты{% endblock %}
{% block meta %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="keywords" content="">
    <meta name="description" content="">
{% endblock %}
<!-- IconFont and Stylesheet -->
{% block link %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/fontawesome.min.css" integrity="sha512-siarrzI1u3pCqFG2LEzi87McrBmq6Tp7juVsdmGY1Dr8Saw+ZBAzDzrGwX3vgxX1NkioYNCFOVC0GpDPss10zQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js'></script>
{% endblock %}
<!--//-->

{% block content %}
    
    {% include "navbar.html" %}

    <!--Top side semi-circle design-->
    <div class="d-none d-sm-block div-semi-circle"></div> 
    <div class="d-none d-sm-block div-semi-circle-smaller"></div>
    <div class="d-none d-sm-block div-semi-circle-ontop"></div>  
    <!--//-->


    <div class="plates_home main_plate container-custom plate-container">
        <h4 class="mt-5 mb-4 " style="font-size:23px; color:var(--nav-bg)">ИНСТИТУТЫ</h4>
            <hr style="color:var(--nav-btn-bg)">
        {% if institutes %}

        {% for i, img in institutes %} <!--This loop repeats the div below exactly 9 times-->
      
        <div  id="first_plate" class="mt-4 plates mb-5 col-lg-12 col-sm-12 col-md-12 col-xs-12 position-relative">
            
            <div class="title limit"><h3 class="big_title" style="line-height:30px; padding-left:3em; padding-right:4em">
                {{ i.name |default_if_none:""|slice:":100" }}{% if i.name|length > 100 %}...{% endif %}
            </h3></div>

            <div class="row container-custom rounded " style="background-color:white; width:99%" >
                <div class="mb-4 c col-lg-9 col-md-9 col-sm-8 col-xs-8" >
                    <div class="row">
                   
                        <div class="col-lg-11 col-md-11 col-sm-12 rounded" style="background-color:white">
                            
                            <div class="container mt-4">
                                <div class="mt-2">
                                    <h3 style="color:var(--nav-bg-darker); font-size:14px; " class="limit">ФИО председателя<span style="color:black">: {{ i.chairman |default_if_none:""|slice:":45" }}{% if i.chairman|length > 45 %}...{% endif %}</span></h3><hr style="color:silver">
                                </div> 
                                
                                <div class="mt-4">
                                    <h3 style="color:var(--nav-bg-darker); font-size:14px; line-height:20px; " class="limit">Количество сотрудников<span style="color:black">: {{i.employees_count}}</span></h3><hr style="color:silver">
                                </div>

                                <div class="mt-4">
                                    <h3 style="color:var(--nav-bg-darker); font-size:14px; line-height:20px; ">Количество молодых учёных<span style="color:black">: {{i.scientist_count}}</span></h3><hr style="color:silver">
                                </div>	
                                
                                <div class="mt-4">
                                    <h3 style="color:var(--nav-bg-darker); font-size:14px">Описание:</h3>
                                    <p style="color:black" class="limitp">{{i.description}}</p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="mt-4 mb-4 rounded col-lg-3 col-md-3 col-sm-4 col-xs-4 institute-right-div d-flex align-items-center justify-content-center" >
                    <div class="text-center mt-3 mb-3 d-flex align-items-center justify-content-center">
                        {% if img %}
                            <img src="/media/{{img.url_path}}" class="rounded img-fluid align-items-center justify-content-center"  style="height: 200px width:300px ;" alt="{{img.alt}}">
                        {% else %}
                            <img src="https://marketplace.canva.com/EAFCh_1S8lw/2/0/400w/canva-gold-and-black-luxury-estate-agency-logo-J8_Ruw9_2Zw.jpg" class=" img-fluid align-items-center justify-content-center"  style=" border:4px solid black" width="100%" alt="...">
                        {% endif %}
                    </div>
                </div>
            </div>
            <a class="stretched-link" href="{% url 'info:institute_info' i.id %}"></a>
        </div>
        {% endfor %}
        {% else %}
        <div class="container plates mt-2 " style="max-width:700px">
            <h4 class="text-center" style="margin-top:6em; line-height:22px; font-family:Arial,Helvetica,sans-serif; padding:5em; color: grey">ИНСТИТУТЫ не найдены.</h4>
            <h1 style="margin-top:-1em; color:white; background-color: rgba(146,0,0,0.5)" class="text-center rounded"><i class="fa fa-exclamation-triangle "></i></h1><br/>
          </div>

        {% endif %}
      
<!--        <div  id="first_plate" class="mt-5 plates mb-5 col-lg-12 col-sm-12 col-md-12 col-xs-12 position-relative">-->
<!--            <div class="row container-custom">-->
<!--                <div class="mt-4 mb-4 c col-lg-9 col-md-9 col-sm-8 col-xs-8">-->
<!--                    <div class="row">-->
<!--                   -->
<!--                        <div class="col-lg-11 col-md-11S col-sm-12 rounded" style="">-->
<!--                            <h3 style="color:var(&#45;&#45;nav-bg); font-size:14px">Описание гранта</h3><hr style="color:silver">-->
<!--                            <div class="mt-2">-->
<!--                                <p style="color:black">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley </p>-->
<!--                            </div>-->
<!--                            -->
<!--                            <div class="mt-4">-->
<!--                                <h3 style="color:var(&#45;&#45;nav-bg); font-size:14px">Количество сотрудников<span style="color:black">: 2000</span></h3><hr style="color:silver">-->
<!--                            </div>-->

<!--                            <div class="mt-4">-->
<!--                                <h3 style="color:var(&#45;&#45;nav-bg); font-size:14px">Количество молодых учёных<span style="color:black">: 2000</span></h3><hr style="color:silver">-->
<!--                            </div>-->

<!--                            <div class="mt-4">-->
<!--                                <h3 style="color:var(&#45;&#45;nav-bg); font-size:14px">ФИО председателя<span style="color:black">: Фамилия Имя Отчество</span></h3><hr style="color:silver">-->
<!--                            </div>-->
<!--                        </div>-->

<!--                    </div>-->
<!--                </div>-->
<!--                <div class="mt-4 mb-4 rounded col-lg-3 col-md-3 col-sm-4 col-xs-4 institute-right-div">-->
<!--                    <div class="text-center mt-3 mb-3">-->
<!--                        <img src="https://marketplace.canva.com/EAFCh_1S8lw/2/0/400w/canva-gold-and-black-luxury-estate-agency-logo-J8_Ruw9_2Zw.jpg" class=" img-fluid"  style=" border:4px solid black" width="100%" alt="...">-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--            <a class="stretched-link" href="{% url 'info:institute_info' 1 %}"></a>-->
<!--        </div>-->



    {% if institutes %}
        <div class="mt-5">
        <nav aria-label="...">
            <ul class="pagination">
              
            {% if institutes.has_previous %}
                {# whether the previous page exists #}
                {# link to the prev page #}
                
                  <li class="page-item ">
                    <a class="page-link" href="?page={{grants.previous_page_number}}" tabindex="-1">Previous</a>
                  </li>
                  <li class="page-item"><a class="page-link" href="?page={{grants.previous_page_number}}">{{grants.previous_page_number}}</a></li>
                
              {% else %}
                {# If previous page does not exist  #}
                {# Disaplay a disabled link  #}
                <li class="page-item disabled">
                  <a class="page-link" href="" tabindex="-1">Previous</a>
                </li>

            {% endif %}


            <li class="page-item active">
              <a class="page-link" href="#">{{grants.number}} <span class="sr-only">(current)</span></a>
            </li> {# the current page number #}

            {%if grants.has_next %} {# whether the next page exists #}
                {# link to the next page #}
               
                    
                    
                    <li class="page-item"><a class="page-link" href="?page={{grants.next_page_number}}">{{grants.next_page_number}}</a></li>
                    <li class="page-item">
                      <a class="page-link" href="?page={{grants.next_page_number}}">Next</a>
                    </li>

              {% else %}
                  <li class="page-item disabled">
                    <a class="page-link" href="">Next</a>
                  </li>
                  
            {% endif %}

            </ul>
          </nav>
        </div>
        {% endif %}


    </div>

        


    {% include "footer.html" %}

    <!-- Javascript Inc-->
    <script src="{% static 'js/nav-bar.js' %}"></script>
{% endblock %}