smu_site/apps/SHC/urls.py
from django.urls import path
from . import views


app_name = "SHC"

urlpatterns = [
    path('', views.index, name='index'),
]

smu_site/apps/documents/urls.py
from django.urls import path
from . import views


app_name = 'documents'

urlpatterns = [
    path('', views.index, name='index')
]

smu_site/apps/info/urls.py
from django.urls import path
from . import views


app_name = 'info'

urlpatterns = [
    path('organization/', views.organization, name='organization'),
    path('institutes/', views.institutes, name='institutes'),
    path('grant/', views.grant, name='grant'),
    path('gzs/', views.gzs, name='gzs'),
    # path('newspage/', views.newspage, name='newspage'),
    path('institutes/<int:inst_id>/', views.institute_info,
         name='institute_info')
]

smu_site/apps/moderators/urls.py
from django.urls import path
from . import views

app_name = 'moderators'

urlpatterns = [
    path('account/create_grant', views.create_new_grant, name='create_grant'),
    path('account', views.create_news, name='news'),
    path('account/save_news', views.save_news, name='save_news'),
    path('account/moder_guests', views.moder_guests, name='moder_guests'),
    path('account/gzs', views.gzs, name='gzs'),
    path('account/add_new_guests', views.add_new_guests, name='add_new_guests'),
    path('account/create_new_institute', views.create_new_institute, name='create_institute'),
    path('account/add_new_documents', views.add_new_documents, name='add_new_documents'),
    path('account/create_scientist', views.create_scientist, name='create_scientist'),
]

smu_site/apps/news/urls.py
from django.urls import path
from . import views


app_name = 'news'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:news_id>/', views.newspage, name='newspage'),
    path('events/<int:event_id>/', views.eventpage, name='eventpage'),
]

smu_site/apps/representatives/urls.py
from django.urls import path
from . import views


app_name = 'representatives'

urlpatterns = [
    path('account', views.create_news, name='news'),
    path('account/save_news', views.save_news, name='save_news'),
    path('account/create_scientist', views.create_scientist, name='create_scientist'),
    # path('account/create_new_institute', views.create_new_institute, name='create_institute'),
    # path('account/create_new_grant', views.create_new_grant, name='create_new_grant'),
    path('account/upload_doc', views.upload_doc, name='upload_doc'),
    # path('<int:institute_id>/', views.create_scientist, name='index'),
]

smu_site/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views, settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='main'),
    path('news/', include('news.urls'), name='news'),
    path('documents/', include('documents.urls')),
    path('info/', include('info.urls')),
    path('moderators/', include('moderators.urls')),
    path('accounts/login', include('django.contrib.auth.urls')),
    path('accounts/login', views.user_login, name='user_login'),
    # path('representatives/', include(
    #      ('representatives.urls', 'representatives'),
    #      namespace='representatives')),
    path('representatives/', include('representatives.urls')),
    path('SHC/', include('SHC.urls')),
    path('delete/<str:obj_type>/<int:id>', views.readelete, name='delete_news'),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

smu_site/apps/SHC/models.py
from django.db import models


class Doc(models.Model):
    doc = models.OneToOneField('documents.Doc',
                               on_delete=models.CASCADE,
                               verbose_name='id документа',
                               primary_key=True)
    description = models.TextField('Описание документа')
    on_changed = models.BigIntegerField('ID заменяемой записи',
                                        null=True)

smu_site/apps/documents/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField("Название категории", max_length=300)


class Doc(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    queue = models.OneToOneField("moderators.Queue",
                                 on_delete=models.SET_NULL, null=True)
    name = models.CharField("Название документа", max_length=100)

    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 null=True)
    
    def _img_dir_path(self, filename):
        return (f'documents/'
                f'{self.category.name}'
                f'/{filename}')
    
    path = models.FileField("Путь до документа",
                            upload_to=_img_dir_path)
    

smu_site/apps/moderators/models.py
from django.db import models


class Queue(models.Model):
    CHOICES = (
        ('doc', 'Документ'),
        ('news', 'Новость'),
        ('event', 'Мероприятие/событие'),
        ('scientist', 'Учёный')
    )
    obj_type = models.CharField("Тип объекта",
                                max_length=10, choices=CHOICES)
    
    SCHOICES = (
        ('pub', 'Публикация'),
        ('chg', 'Изменение'),
        ('del', 'Удаление')
    )
    status = models.CharField("Статус запрашиваемого объекта",
                              max_length=10, choices=SCHOICES,
                              default='Публикация')
    
    class Meta:
        verbose_name = 'Очередь'
        verbose_name_plural = 'Очереди'

smu_site/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth import authenticate


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Имя пользователя",
        'required': "",
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'id': "myInput",
        'placeholder': "пароль",
        'required': "",
    }))

    def clean_password(self):
        cd = self.cleaned_data
        user = authenticate(username=cd['username'], password=cd['password'])
        if user is None:
            raise ValidationError('')
        return cd['password']

    def clean_username(self):
        cd = self.cleaned_data
        return cd['username']

smu_site/apps/SHC/views.py
from django.conf import settings
from django.shortcuts import render
# from documents.models import Doc
from .models import Doc as SHCDoc


def index(request):
    documents = (SHCDoc.objects.select_related('documents.doc')
                 .filter(doc__queue_id__isnull=True)
                 .order_by('documents.doc__id'))
    # print(documents)
    return render(request, 'SHC/index.html',
                  {'docs': documents, 'media': settings.MEDIA_URL})

smu_site/apps/documents/views.py
from django.shortcuts import render
from django.conf import settings
from .models import Category, Doc


def index(request):
    docs = (Doc.objects.select_related('category')
            .filter(queue_id__isnull=True,
                    category__isnull=False).order_by('category__name',
                                                     'name'))
    docs_content = {}
    for d in docs:
        if not docs_content.get(d.category.name):
            docs_content[d.category.name] = ["", 0]

        docs_content[d.category.name][0] += (
            "<div class='doc_content_stuff'>"
            f"<a href='{settings.MEDIA_URL}"
            f"{d.path}'>{d.name}</a></div>\n")
        docs_content[d.category.name][1] = d.id

    return render(request, 'info/documents.html',
                  {'title': "Документы",
                   'categories': [(c, *docs_content[c]) for c in docs_content],
                   "is_moder": request.user.groups.filter(name='moderator').exists(),
                   "is_repr": request.user.groups.filter(name='representative').exists()
                   })

smu_site/apps/info/views.py
import configparser

from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, Http404

from info.models import Institute, Scientist, Grant
from news.models import Image
from SHC.models import Doc as SHCDoc


config = configparser.ConfigParser()
config.read('config.ini')


# def newspage(request):
#     return render(request, 'info/newspage.html')

def institutes(request):
    inst = Institute.objects.all().order_by('name')
    inst = [(i, Image.objects.filter(institute_id=i.id)
             .order_by('id').first())
            for i in inst]
    return render(request, 'info/institutes.html',
                  {'institutes': inst,
                   "is_moder": request.user.groups.filter(
                       name='moderator').exists(),
                   "is_repr": request.user.groups.filter(
                       name='representative').exists()
                   })


def grant(request):
    grants = (Grant.objects.filter(queue_id__isnull=True)
              .order_by('end_doc_date'))
    grants = [(g, Image.objects.filter(grant_id=g.id)
               .order_by('id').first())
              for g in grants]
    
    p = Paginator(grants, int(config["news"]["grants_per_page"]))
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        # Если page_number не является целым числом, то присваивается 1
        page_obj = p.page(1)
    except EmptyPage:
        # Если страница пустая, возвращает последнюю страницу
        page_obj = p.page(p.num_pages)
        
    return render(request, 'info/grant.html',
                  {'grants': page_obj,
                   "is_moder": request.user.groups
                   .filter(name='moderator').exists(),
                   "is_repr": request.user.groups
                   .filter(name='representative').exists()
                   })


def organization(request):
    return render(request, 'info/organization.html',
                  {
                      "is_moder": request.user.groups
                      .filter(name='moderator').exists(),
                      "is_repr": request.user.groups
                      .filter(name='representative').exists()})


def gzs(request):
    documents = (SHCDoc.objects.select_related('doc')
                 .filter(doc__queue_id__isnull=True)
                 .order_by('doc__id'))
    return render(request, 'info/gzs.html',
                  {
                      'docs': documents,
                      'media': settings.MEDIA_URL,
                      "is_moder": request.user.groups
                      .filter(name='moderator').exists(),
                      "is_repr": request.user.groups
                      .filter(name='representative').exists()})


def institute_info(request, inst_id):
    try:
        inst = Institute.objects.get(id=inst_id)
    except:
        return Http404('Институт не найден')
    
    inst_img = Image.objects.filter(institute_id=inst_id).first()
    scientists = (Scientist.objects.filter(institute_id=inst_id,
                                           queue_id__isnull=True)
                  .order_by('name'))
    scientists = [(s, Image.objects.filter(scientist_id=s.id)
                   .order_by('id').first())
                  for s in scientists]
    return render(request, 'info/institute_info.html',
                  {
                      'institute': inst,
                      'inst_img': inst_img,
                      'scientists': scientists,
                      "is_moder": request.user.groups.filter(
                          name='moderator').exists(),
                      "is_repr": request.user.groups.filter(
                          name='representative').exists()
                  })

smu_site/apps/news/views.py
import configparser

from bs4 import BeautifulSoup as BS
from datetime import date, timedelta
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from django.shortcuts import render
from django.utils.timezone import localdate

from .models import News, Event, Image
from info.models import Grant


def newspage(request, news_id):
    try:
        news = News.objects.get(id=news_id)
    except:
        return Http404('Такой новости не существует')
    
    month = ['Янв', 'Февр', 'Март', 'Апр', 'Май', 'Июнь',
             'Июль', 'Авг', 'Сент', 'Окт', 'Нояб', 'Дек']
    m = month[news.pub_date.month - 1]
    
    img = Image.get_related_images(news_id, 'news')
    if img:
        img = img[0]
    
    return render(request, 'news/newspage.html',
                  {'content': news, 'type': 'news',
                   'img': img, 'month': m,
                   "is_moder": request.user.groups
                   .filter(name='moderator').exists(),
                   "is_repr": request.user.groups
                   .filter(name='representative').exists()})


def eventpage(request, event_id):
    try:
        event = Event.objects.get(id=event_id)
    except:
        return Http404('Такой новости не существует')
    
    month = ['Янв', 'Февр', 'Март', 'Апр', 'Май', 'Июнь',
             'Июль', 'Авг', 'Сент', 'Окт', 'Нояб', 'Дек']
    m = month[event.pub_date.month - 1]
    
    img = Image.get_related_images(event_id, 'event')
    if img:
        img = img[0]
        
    return render(request, 'news/newspage.html',
                  {'content': event, 'type': 'event', 'img': img,
                   'month': m,
                   "is_moder": request.user.groups
                   .filter(name='moderator').exists(),
                   "is_repr": request.user.groups
                   .filter(name='representative').exists()})


config = configparser.ConfigParser()  # создаём объекта парсера
config.read("config.ini")


def index(request):
    # Получаем даты для фильтрации списка новостей
    sdate = date.fromisoformat(
        request.POST.get("start-date", "2023-11-28"))
    edate = date.fromisoformat(
        request.POST.get("end-date", localdate().isoformat()))
    edate += timedelta(days=1)
    
    # Выбираем те новости и события, которые не находятся в очереди
    last_news = News.objects.filter(
        pub_date__range=(sdate, edate), queue_id__isnull=True)
    last_news = [(n, Image.objects.filter(news_id=n.id).first())
                 for n in last_news]
    last_events = Event.objects.filter(
        pub_date__range=(sdate, edate), queue_id__isnull=True)
    last_events = [(e, Image.objects.filter(event_id=e.id).first())
                   for e in last_events]
    last_news += last_events
    
    # Сортируем по дате и выбираем первые 5 для первой страницы новостей
    # в будущем нужно реализовать pagination
    last_news = list(sorted(last_news, key=lambda x: x[0].pub_date,
                            reverse=True))
    
    # функция для сокращения текста
    def trim_text(text: str, limit):
        if len(text) < limit:
            return text
        
        si1 = text.find('. ')
        si2 = text.find('! ')
        si3 = text.find('? ')
        if max(si1, si2, si3) != -1:
            si = min(i for i in (si1, si2, si3) if i != -1)
            if si < limit:
                return text[:si + 2] + trim_text(text[si + 2:],
                                                 limit - si - 1)
        
        if ' ' in text:
            t = ''
            for w in text.split(' '):
                if len(t) + len(w) < limit:
                    t += w + ' '
                else:
                    break
            
            return t + ' ...'
        
        return text[:limit - 3] + '...'
    
    # объединяем со списков месяцев и кратким текстом
    month = ['Янв', 'Февр', 'Март', 'Апр', 'Май', 'Июнь',
             'Июль', 'Авг', 'Сент', 'Окт', 'Нояб', 'Дек']
    last_news = [('news' if isinstance(n, News) else 'event',
                  n, month[n.pub_date.month - 1],
                  trim_text(BS(n.text, 'html.parser')
                            .select_one('p').text, 280), img)
                 for n, img in last_news]
    
    p = Paginator(last_news, int(config["news"]["news_per_page"]))
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        # Если page_number не является целым числом, то присваивается 1
        page_obj = p.page(1)
    except EmptyPage:
        # Если страница пустая, возвращает последнюю страницу
        page_obj = p.page(p.num_pages)
    
    # переводим даты в изначальный формат
    sdate = sdate.isoformat()
    edate -= timedelta(days=1)
    edate = edate.isoformat()
    
    # Получаем актуальные события и гранты
    events = (Event.objects.filter(queue_id__isnull=True)
              .order_by('begin_date', '-pub_date'))[
             :int(config["news"]["events_per_page"])]
    events = [(e, trim_text(BS(e.text, 'html.parser')
                            .select_one('p').text, 180))
              for e in events]
    grants = (Grant.objects.filter(queue_id__isnull=True)
              .order_by('end_doc_date'))[:3]
    
    return render(request, 'index.html',
                  {
                      "is_moder": request.user.groups
                  .filter(name='moderator').exists(),
                      "is_repr": request.user.groups
                  .filter(name='representative').exists(),
                      "last_news": page_obj,
                      "sdate": sdate,
                      "edate": edate,
                      "events": events,
                      "grants": grants
                  })

smu_site/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="icon" href="{% static 'img/logo_smu.png' %}" type="image/x-icon">
    {% block meta %}{% endblock %}

    {% block link %}{% endblock %}
    <title>{% block title %}Совет молодых учёных ДВО РАН{% endblock %}</title>
    <script src="{% static 'js/theme.js' %}"></script>
    
</head>
<body>
    {% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    
    <script>
      $(document).ready(function(){
        $('.carousel').slick({
          autoplay: true,
          autoplaySpeed: 2000, // Adjust the speed in milliseconds
          dots: true, // Display dots for navigation
          infinite: true,
          slidesToShow: 1,
          slidesToScroll: 1
        });
      });
    </script>
</body>
</html>

smu_site/templates/footer.html
    <footer class="footer">
        <div class="container row justify-content-between">    
            <div class="footer-col">
               
				<h4>Связь с администратором</h4>
                <ul style="color:whitesmoke">
					<li>Электронная почта: example@mail.ru</li>
                    <li>Контактный телефон: 8 800 555 35-35</li>
                </ul>
            </div>

            <div class="footer-col">
                    <div class="dropdown">
                        <button class="dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            выберите тему страницы
                        </button>
                        
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" id="light-mode-toggless">Default Theme</a>
                            <a class="dropdown-item" id="dark-mode-toggless">Dark Mode</a>
                            <a class="dropdown-item" id="black-mode-toggless">Black Mode</a>
                        
                        </div>
                      </div>
            </div>
            
            <div class="footer-col">
                <h4>Мы в сотсетях</h4>
                <div class="social-links">
                    <a href="#" class="bi bi-telegram"></a>
                </div><br/>

                {% if user.is_authenticated %}
                    <a href="{% url 'logout'%}?next={% url 'main' %}" class="login-btn">Выйти</a>
                {% else %}
                    <a href="{% url 'user_login'%}?next={{ request.path }}" class="login-btn">Вход</a>
                {% endif %}

            </div>
        </div>
    </footer>

    

    <!-- Javascript Inc-->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js'></script>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"/>

smu_site/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top">
    
    <img src="{% static 'img/logo_smu_transparent.png' %}"  class="d-none d-sm-block" style="margin-left:25px; margin-right:25px; height:60px; width:60px;" alt="Logo Image">
    <h3 class="mt-1  text-white text d-none d-sm-block" style="font-size:18px; margin-right:25px"> СМУ ДВО РАН </h3>
    
    <!--For extra small screens-->
    <img src="{% static 'img/logo_smu.png' %}"  class="d-block d-sm-none" style="margin-left:25px; margin-right:25px; height:40px; width:40px;" alt="Logo Image">
    <h3 class="mt-1  text-white text d-block d-sm-none" style="font-size:12px; margin-left:-25px; margin-right:3px"> СМУ ДВО РАН </h3>
    <!--For extran small screens-->

    <button class="navbar-toggler"  type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"  style="" >
        <span class="navbar-toggler-icon" style="color:red;" ></span>
    </button>

    <div class="container-lg">
       

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'news:index' %}">Новости</a><span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'info:grant' %}">Гранты</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'info:institutes' %}">Институты</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'documents:index' %}">Документы</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'info:gzs' %}">ГЖС</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'info:organization' %}">Об организации</a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item">
                    {% if is_moder or user.is_superuser %}
                    <a class="nav-link" href="{% url 'moderators:news' %}">Профиль</a>
                    {% elif is_repr %}
                    <a class="nav-link" href="{% url 'representatives:news' %}">Профиль</a>
                    {% endif %}
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>